---

#===========================================================================
# vCenter Organizational Structure
#===========================================================================

- name: Create Cluster Folder
  community.vmware.vcenter_folder:
    hostname: '{{ provider.credentials.vcenter_hostname }}'
    username: '{{ provider.credentials.vcenter_username }}'
    password: '{{ provider.credentials.vcenter_password }}'
    validate_certs: '{{ provider.credentials.vcenter_verify_ssl }}'
    datacenter_name: "{{ provider.configuration.vcenter_datacenter }}"
    folder_name: "{{ cluster_name }}"
    folder_type: vm
    state: present
  tags:
    - vmware_tasks
    - vmware_create_folder

- name: Create the ISOs directory on the datacenter/datastore
  community.vmware.vsphere_file:
    host: '{{ provider.credentials.vcenter_hostname }}'
    username: '{{ provider.credentials.vcenter_username }}'
    password: '{{ provider.credentials.vcenter_password }}'
    validate_certs: '{{ provider.credentials.vcenter_verify_ssl }}'
    datacenter: "{{ provider.configuration.vcenter_datacenter }}"
    datastore: "{{ provider.configuration.vcenter_datastore }}"
    path: /ISOs
    state: directory
  tags:
    - vmware_tasks
    - vmware_create_iso_directory

#===========================================================================
# Upload ISO
#===========================================================================

- name: Check for the ISO
  community.vmware.vsphere_file:
    host: '{{ provider.credentials.vcenter_hostname }}'
    username: '{{ provider.credentials.vcenter_username }}'
    password: '{{ provider.credentials.vcenter_password }}'
    validate_certs: '{{ provider.credentials.vcenter_verify_ssl }}'
    datacenter: "{{ provider.configuration.vcenter_datacenter }}"
    datastore: "{{ provider.configuration.vcenter_datastore }}"
    path: "ISOs/ocp-ai-{{ cluster_id }}.iso"
    state: file
  ignore_errors: true
  register: vmware_check_for_iso
  tags:
    - vmware_tasks
    - vmware_check_for_iso

- name: Upload Discovery ISO to the target Cluster Store
  when: vmware_check_for_iso.state == "absent"
  community.vmware.vsphere_copy:
    hostname: '{{ provider.credentials.vcenter_hostname }}'
    username: '{{ provider.credentials.vcenter_username }}'
    password: '{{ provider.credentials.vcenter_password }}'
    validate_certs: '{{ provider.credentials.vcenter_verify_ssl }}'
    datacenter: "{{ provider.configuration.vcenter_datacenter }}"
    datastore: "{{ provider.configuration.vcenter_datastore }}"
    src: "{{ generated_asset_directory }}/{{ cluster_id }}/ocp_ai.iso"
    path: "ISOs/ocp-ai-{{ cluster_id }}.iso"
  ignore_errors: true
  tags:
    - vmware_tasks
    - vmware_upload_ova
